<?php
//ind_logo_projektu.inc;
        if($Projekt->kod == "NSP") {
?>
            <font style="color:white; font-weight:bold; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size:18px;">PROJEKT NAJDI SI PRÁCI V PLZEŇSKÉM KRAJI</FONT><br>
            <img src="../loga/logoNSP.gif" alt="Logo projektu Najdi si práci">
            <hr>
<?php
        }
        if($Projekt->kod == "PNP") {
?>
            <font style="color:white; font-weight:bold; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size:18px;">PROJEKT PŘÍPRAVA NA PRÁCI V PLZEŇSKÉM KRAJI</FONT><br>
            <img src="../loga/logoPNP.gif" alt="Logo projektu Příprava na práci">
            <hr>
<?php
        }
if($Projekt->kod == "SPZP") {
?>
            <font style="color:white; font-weight:bold; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size:18px;">PROJEKT S POMOCÍ ZA PRACÍ</FONT><br>
            <img src="../loga/logo_spzp.jpg" alt="Logo projektu S pomocí za prací">
            <hr>
<?php
        }

if($Projekt->kod == "RNH") {
?>
            <font style="color:white; font-weight:bold; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size:18px;">PROJEKT RODINA NENÍ HANDICAP</FONT><br>
            <img src="../loga/logo_rnh.jpg" alt="Logo projektu Rodina není handicap">
            <hr>
<?php
        }

